### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by hakandingenc** [0xb0bb/karkinos#4]
I am on macOS Big Sur 11.6:

```
❯ ./kark.py --help
downloading: https://raw.githubusercontent.com/0xb0bb/karkinos/master/db/libs.json (162b)
extracting:  glibc.db.xz
xz: /Users/*****/****************/****/************/*/karkinos/db/glibc.db.xz: File format not recognized
error: glibc.db.xz failed; mismatched hash
```

```
❯ xz --version
xz (XZ Utils) 5.2.5
liblzma 5.2.5
```

What might be causing this?

**Comment by 0xb0bb** [comment]
I think this must be caused by the fact you do not have `Git-LFS` installed: https://git-lfs.github.com/ 
Usually you can install it with: `git lfs install`

After you have it installed, clone the repo again and it should work.

This is required to use larger files on github, I was thinking of finding a workaround or documenting
this better but hadn't gotten around to it. Let me know if that helps so I can close the issue.

**Comment by hakandingenc** [comment]
That fixed it. Thanks.
